version: '2'
services:
  kickstarter_django:
    image: pratio/kickstarter_django
    container_name: ks_django
    command: gunicorn kickstarter_django.wsgi:application -w 2 -b :8000
    env_file:
      - kickstarter.env
    working_dir: /usr/src/kickstarter_django
    expose:
      - "8000"
    links:
      - kickstarter_db
    ports:
      - "8000:8000"
  kickstarter_db:
    restart: always
    image:  pratio/kickstarter_postgres
    container_name: ks_db
    ports:
      - "5434:5434"



