# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryStatusCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(blank=True, null=True)),
                ('canceled', models.IntegerField(blank=True, null=True)),
                ('failed', models.IntegerField(blank=True, null=True)),
                ('live', models.IntegerField(blank=True, null=True)),
                ('successful', models.IntegerField(blank=True, null=True)),
                ('suspended', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'category_status_count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryStatusPercent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(blank=True, null=True)),
                ('canceled', models.IntegerField(blank=True, null=True)),
                ('failed', models.IntegerField(blank=True, null=True)),
                ('live', models.IntegerField(blank=True, null=True)),
                ('successful', models.IntegerField(blank=True, null=True)),
                ('suspended', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'category_status_percent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CountryStatusCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField(blank=True, null=True)),
                ('canceled', models.IntegerField(blank=True, null=True)),
                ('failed', models.IntegerField(blank=True, null=True)),
                ('live', models.IntegerField(blank=True, null=True)),
                ('successful', models.IntegerField(blank=True, null=True)),
                ('suspended', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'country_status_count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CountryStatusPercent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField(blank=True, null=True)),
                ('canceled', models.IntegerField(blank=True, null=True)),
                ('failed', models.IntegerField(blank=True, null=True)),
                ('live', models.IntegerField(blank=True, null=True)),
                ('successful', models.IntegerField(blank=True, null=True)),
                ('suspended', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'country_status_percent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kickstarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(blank=True, null=True)),
                ('disable_communication', models.TextField(blank=True, null=True)),
                ('location_type', models.TextField(blank=True, null=True)),
                ('category_parent_id', models.IntegerField(blank=True, null=True)),
                ('sub_category', models.TextField(blank=True, null=True)),
                ('usd_pledged', models.TextField(blank=True, null=True)),
                ('launched_at', models.TextField(blank=True, null=True)),
                ('category_slug', models.TextField(blank=True, null=True)),
                ('currency', models.TextField(blank=True, null=True)),
                ('deadline', models.TextField(blank=True, null=True)),
                ('spotlight', models.TextField(blank=True, null=True)),
                ('currency_trailing_code', models.TextField(blank=True, null=True)),
                ('displayable_name', models.TextField(blank=True, null=True)),
                ('state_changed_at', models.TextField(blank=True, null=True)),
                ('goal', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('creator_name', models.TextField(blank=True, null=True)),
                ('staff_pick', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('pledged', models.TextField(blank=True, null=True)),
                ('creator', models.TextField(blank=True, null=True)),
                ('location_code', models.TextField(blank=True, null=True)),
                ('slug', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('static_usd_rate', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('backers_count', models.TextField(blank=True, null=True)),
                ('currency_symbol', models.TextField(blank=True, null=True)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.TextField(blank=True, null=True)),
                ('blurb', models.TextField(blank=True, null=True)),
                ('category_position', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ks_project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MonthStatusCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.TextField(blank=True, null=True)),
                ('canceled', models.IntegerField(blank=True, null=True)),
                ('failed', models.IntegerField(blank=True, null=True)),
                ('live', models.IntegerField(blank=True, null=True)),
                ('successful', models.IntegerField(blank=True, null=True)),
                ('suspended', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'monthly_status_count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MonthStatusPercent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.TextField(blank=True, null=True)),
                ('canceled', models.IntegerField(blank=True, null=True)),
                ('failed', models.IntegerField(blank=True, null=True)),
                ('live', models.IntegerField(blank=True, null=True)),
                ('successful', models.IntegerField(blank=True, null=True)),
                ('suspended', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'monthly_status_percent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('creator_name', models.TextField(blank=True, null=True)),
                ('blurb', models.TextField(blank=True, null=True)),
                ('backers_count', models.TextField(blank=True, null=True)),
                ('goal', models.TextField(blank=True, null=True)),
                ('pledged', models.TextField(blank=True, null=True)),
                ('percent_of_goal', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('sub_category', models.TextField(blank=True, null=True)),
                ('launched_at', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'projects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubCategoryStatusCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.TextField(blank=True, null=True)),
                ('canceled', models.IntegerField(blank=True, null=True)),
                ('failed', models.IntegerField(blank=True, null=True)),
                ('live', models.IntegerField(blank=True, null=True)),
                ('successful', models.IntegerField(blank=True, null=True)),
                ('suspended', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sub_category_status_count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubCategoryStatusPercent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.TextField(blank=True, null=True)),
                ('canceled', models.IntegerField(blank=True, null=True)),
                ('failed', models.IntegerField(blank=True, null=True)),
                ('live', models.IntegerField(blank=True, null=True)),
                ('successful', models.IntegerField(blank=True, null=True)),
                ('suspended', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sub_category_status_percent',
                'managed': False,
            },
        ),
    ]
